### ISSUE TITLE
Site structure

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-server#11]
* There's a mix of dynamic and static content under /banjir/language_code/data/api/, which means that any robots file will have to specify subfolders of the api folder and be upgraded if they ever change / are added to. Also means that nginx rules for static content paths (to speed up serving and reduce CPU load) would be unnecessarily difficult.
* Having api (for actual API calls, not the static content currently at /banjir/language_code/data/api/ ) as a top level path instead of sitting under /banjir also helps with nginx configuration to speed up static content and reduce separate code.
* The API is duplicated under each language code. Having it separate to /banjir/ would help with that too. Having the site return pages based on browser request instead of having them as separate paths is not good either. This aspect is is covered in part by [petajakarta-web issue #46](https://github.com/smart-facility/petajakarta-web/issues/46), but you'd also need to make necessary changes to the server code, I guess.

**Comment by talltom** [comment]
* The API is not duplicated under different languages. Only the documentation which sits at 
http://petajakarta.org/banjir/en/data/api/ or http://petajakarta.org/banjir/in/data/api/. For example http://petajakarta.org/banjir/en/data/api/v1/reports/confirmed returns a 404.

* Thus:
    - everything below a language designation is static
    - everything not with a language designation and below /v1/ is dynamic

Does that help?

**Comment by matthewberryman** [comment]
Ah, yes, you're right. My bad for not checking in more detail. This helps enormously. I will set up a test environment to get this right, as it's somewhat easy to break things with EB and nginx.
