### ISSUE TITLE
Unable to put robots.txt in /

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-server#12]
On realising that I'd put robots.txt in the wrong location, I went to fix this in [petajakarta-web 2d021f4](https://github.com/smart-facility/petajakarta-web/commit/2d021f4d1a7a8a800ecfb5f424e5ef656e22eb88) but realised (of course) it's not that simple: cognicity-server needs to be modified to serve this static file under /
@talltom, is there a clean way of doing this?

**Comment by talltom** [comment]
Done. Summary of changes:
1) Moved robots.txt to 'build' in [petajakarta-web 6968cb7](https://github.com/smart-facility/petajakarta-web/commit/6968cb7e8511a1032904e95a023bad5d8c8cd864)
2) Added route for 'robots.txt' to cognicity-server: [cognicity-server 07fe397](https://github.com/smart-facility/cognicity-server/commit/07fe3973610744554ae57d556dd08413459e58d5)

Please test above commits, and confirm it works for you, and I will update cognicitiy-server version.

**Comment by matthewberryman** [comment]
Fixed with https://github.com/smart-facility/cognicity-server/commit/07fe3973610744554ae57d556dd08413459e58d5
