### ISSUE TITLE
Default log file path

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-server#15]
The default log path does not exist on all systems (see #14). Some options here:
1. Improve clarity of the [README.md documentation](https://github.com/smart-facility/cognicity-server/blob/master/README.md) around the need to change it.
2. Test if the directory exists, either
    a. using [this package](https://www.npmjs.com/package/is-there) - I am not concerned about the race condition as we're talking about a system directory that's either there or not; Or 
    b. alternatively we could detect when winston fails to open the log file and open it in the current working directory.
3. Change the default to be the current working directory and then modify .ebextensions to make sure it can be bundled off to an s3 bucket on AWS as per [the docs for that](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.logging.html).

I propose 3 and then still clarify (1).

**Comment by talltom** [comment]
I agree with proposed solution, however would like to clarify the following points. 
- Does this mean our AWS deployment will have a separate config file?
- I suggest we could also add this as a unit test.

**Comment by matthewberryman** [comment]
* Regarding AWS, there's no separate config file for the server, but there is a separate config file for Elastic Beanstalk. Wait until I have submitted the pull request (I need to test in an EB environment first).
* We could but then you'd be introducing a separate npm module just for testing and also the proposed default config is guaranteed to pass. Also, I think unit testing should be for code, and not the presence of a directory.
