### ISSUE TITLE
server test failing if config.pg.conString is valid

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-server#16]
The test of the server code (see cb5f335882659125dc773a70bba3ef184518403a) relies on config.pg.conString being invalid, in order to (as the commit comment says) test all the code up until that point. This is why the test works on travis-ci and jenkins as there's no database present. If, however, it is valid (i.e. database has been set up and config.pg.conString , then the server starts up and keeps running, so the [timeout in the test](https://github.com/smart-facility/cognicity-server/blob/master/test/testServer.js#L16) is hit and the test fails (#14). Annoyingly, this then made it hard to reproduce the issue, as, unless you kill that node process, then the second time you test the server will fail because it couldn't open the TCP port, and so the test passes in a different way. To get the desired behaviour for the test we should set config.pg.conString=null in test-config.js

**Comment by talltom** [comment]
Fixed by #17

**Comment by matthewberryman** [comment]
I don't think we've entirely resolved this. There's still a potential issue if the user runs npm test while an instance of the server is running, in that the test behaviour will differ because it will fail at a different point in the code. To avoid a conflict I have changed the port number for 8082. This is fixed and also documented in #19.
