### ISSUE TITLE
zooming out leaves blank page

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-server#24]
Zooming out on the map leaves a blank page in firefox, chrome and safari (all tested on desktop only so far) despite successful 200 requests for tiles.

**Comment by talltom** [comment]
What does /banjir/data/api/v2/reports/confirmed return?

**Comment by matthewberryman** [comment]
Correctly returns 
HTTP/1.1 204 No Content
Server: nginx/1.9.6
Date: Fri, 06 Nov 2015 04:21:06 GMT
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: X-Requested-With

**Comment by matthewberryman** [comment]
No issues on iOS 9.2 Safari on iPhone 6.

**Comment by matthewberryman** [comment]
Tested on iPad and fine too. Maybe it's in the non-retina-specific code?

**Comment by talltom** [comment]
Just re-created locally, looks like 204 translates to a database query error due to missing tables. If a table exists but is empty, CogniCity should return 200 ({FeatureCollection: null}).

**Comment by matthewberryman** [comment]
Ok (and as discussed, probably different on mobile vs desktop due to leaflet and timing).

**Comment by matthewberryman** [comment]
Have now uploaded the current [sample data](https://github.com/smart-facility/cognicity-schema/tree/2.0.x/sample_data) (just the boundary and water facility data) and it has resolved the issue. Awaiting sample report data.
