### ISSUE TITLE
Reset time window

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-server#26]
We need reset the default time window in server.js at places identified with CHANGEME before release. Currently set to 6 hours for testing but we probably want something shorter for production. Tom had it as 1 hour in 928810e but that may be a little too short during low-medium level flooding.

**Comment by talltom** [comment]
1 hour is fine for final deployment. After that data from the government via CogniCity REM will kick-in.

**Comment by talltom** [comment]
Really, we need to have this as a config file parameter.

**Comment by matthewberryman** [comment]
Done. We'll still need to adjust before final deployment.
