### ISSUE TITLE
Flood sensor API needs to calculate water depth

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-server#40]
The API should use [sensor_data.distance](https://github.com/smart-facility/cognicity-floodsensor/blob/master/schema/cognicity_floodsensor_pg_schema.sql#L34) with [sensor_metadata.height_above_riverbed](https://github.com/smart-facility/cognicity-floodsensor/blob/master/schema/cognicity_floodsensor_pg_schema.sql#L12) to calculate water depth.

**Comment by talltom** [comment]
I suggest that it is till useful to keep the 'distance' and height_above_riverbed parameters for context
* will add "water_depth" to API output
